### ISSUE TITLE
Run Pre-Release Tests

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#121]
Just to make sure things run smoother this time around, here's a list of things we should test:
- [x] proofread docs on paper
- [x] R CMD check --as-cran
  - [x] On OS X (@maxheld83 can do that)
  - [x] On Linux (@aiorazabala you run Linux, right?
  - [x] On Windows `devtools::build_win()` makes this easy
- [x] Bump version number
- [x] Bump date
- [x] draft release notes
- [x] make release
- [x] push to CRAN (that's @aiorazabala )
- [ ] write email to list announcing features

**Comment by maxheld83** [comment]
@aiorazabala : FYI, there's also a neat `devtools::release` function that automatically checks, and then FTPs the package to CRAN; maybe that can make your job easier?

**Comment by aiorazabala** [comment]
The list above is great, we should keep that structure for future releases.

The manual submission to CRAN is quite trivial so that's fine.

**Comment by aiorazabala** [comment]
Done with every release (except writing an email to the list, which is only occasionally)
