### ISSUE TITLE
Conference Call #2

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#258]
# Agenda

> Friday, Sep 4, 2015, 09:00 CEST

## Check in

- [x] how is everyone?
- [x] Indonesia offer

## Collaboration

- [x] github doing ok?
- [x] need to get new people on *early*, get the conversation going

## Ancona

- [x] who is going to talk about what? #192 

### Testing

- [x] we now have some automated **testing**, and should have more #89 
- [x] (remember to set up the account as per #260)
- [x] must increase, add more testing for legacy stuff #259 
- [x] this required `qmethod` `quietly = TRUE` option

### Vignettes

- [x] in the future, move extended documentation to **vignettes** #261 

### Manual Rotation

- [x] there are *two* functions `q.mrot.do` and `q.mrot.choose`
- [x] there are plenty of plotting options, many of them slow, but informative
- [x] in the future, for better graphics #172 or drag-drop #176, maybe spin out to separate package #265 because there *is* no good manual rotation package for R for *any* factor analysis.
- [x] flipping aka inverting is *not* an issue #268 
- [x] re-ordering #273 #263 *was* an issue, required `reorder = FALSE`, can be improved later by taking more from `psych::principal` #274 

### new plots

- [x] scoreplot #14 
- [x] factor composition plot from Brown #94 
- [x] loaplot #93 #94 
- [x] cor matrix plot #92 
- [x] fcolors
- [x] q.rotplot #169 
- [x] ...

### nfactors function

- [x] scree plot #150 
- [x] residuals hypothesis testing #149 
- [x] h2 plot #148 
- [x] parallel analysis

### random stuff

- [x] `qfwe` #129 
- [x] q item sd #126

### Pull requests

Let's go over them :smile: 

- [x] @maxheld83 declined @bobbraswell's rotation PR #215 
- [x] simple things first #61 for `make.distribution`, just a smaller helper
- [x] the big one #97 on visualization, manual rotation
  - [x] testing is OK against old qmethod #242 and PQmethod #256 
  - [x] R CMD check -as-CRAN is ok
  - [x] CRAN in Travis might not be, but that's a known bug #123 
  - [x] just need the rest of the release stuff #121, especially proof-reading

- [ ] (max will do the actual merging later).

### Important issues

- [x] what's up with `forced = FALSE` distributions? Why do we need a vector? #238 :confused:  #246  
- [x] can we really accept orthogonal rotations #95 ?

### Centroid

- [x] [Milestone](https://github.com/aiorazabala/qmethod/milestones/Centroid%20Rotation%20and%20More%20%22Old%20School%22%20Q-Methodology)
- [x] get a clear idea of what would be required, think through implications #15 #228 #227 #226 #225 #222 
- [x] how can that be validated? #227 
- [x] what's with the judgmental reflection #228?

### Qmethod 2.0 (Milestone)

- [x] [Milestone](https://github.com/aiorazabala/qmethod/milestones/2.0)
- [x] modularize more stuff #282, #281, #280 
- [x] streamline data types #277
- [x] more testing #259 
- [x] need package management `packrat` #74: this is an accident waiting to happen
- [x] migrate documentation to roxygen2 #31 

## Authorship

- [x] can we maybe change the citation and the author field to include Aiora and Max #272 and also remember to get DOI #47
