### ISSUE TITLE
make qmethod a "one-stop-shop"

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#26]
... another grab bag of issues, more of a place for discussion than actual, closeable issue.

[Job van Exel](http://www.bmg.eur.nl/english/imta/staff/#exel) recently mentioned that he (and Peter Schmolck?) would like to see a completely new program for q method, and that he'd like it to be a "one-stop-shop", including (in rough order of a q-study, including my own 2-cents):
- ~[ ] Gathering Items~
- [x] Sampling Items -> #5 
- [x] Building distributions (somewhat trivial) -> #4 
- [x] Preparing Paper administration -> #6 
- [x] Preparing **Online Administration** -> #22
- [x] Data Entry -> I actually think this should be done in a _spreadsheet_ editor!
- [x] Data Cleaning -> #9, #10 
- [x] Alternative **Extraction Methods** -> #15 #20 etc.?
- [x] Alternative, Interactive, Visualized **Rotation Methods** -> #13 
- [x] Results: Visualized Factor Arrays -> #14 
- [ ] Results: Template for Reporting -> #23
- [X] Results: Online/interactive reporting -> #25

and, last but not least, 
- [x] a cookbok -> #24

... tbc.

**Comment by maxheld83** [comment]
great, some of this stuff is now actually done in #36 !

**Comment by VerenaKasztantowicz** [comment]
@aiorazabala and @maxheld83 : 
I am very impressed by your work and grateful for your support on Q methodology.  I'm trying to use R and GitHub for my dissertation (The purpose of my study is to explore the pedagogical perceptions of teachers, students and unschooling parents about written language acquisition). 

By now I used the following functions:
- directory structure with submodules in GitHub (1. concourse, 2. sample and  3. my study) 
-  the ´import.q.concourse´ and ´build.q.set` in RStudio
- make.cards with hashing (for me as R-newbie creating the .pdf was like magic. :smile: ) 
- testing: ´import.q.sort´ and ´import.q.feedback´
- and collected data of 40 education students in a first pretest (see pic below! Some told me, it was a great experience for them and they started thinking deeply about the subject. :smile: )

Thank you very much! I liked all these administration tools. At first, it wasn't easy for me to understand the concepts behind, but it all worked fine. 
Now it comes to rotation, q-analyse, visualization ... I'm not sure with that, but I will see.

![anonymqsortierung](https://cloud.githubusercontent.com/assets/6077855/6124469/03238e6e-b10e-11e4-914b-89e99c0de5ca.png)

**Comment by aiorazabala** [comment]
Fantastic, thank you @VerenaKasztantowicz !
