### ISSUE TITLE
Small enhancements for next release

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#77]
- [x] In `qdc`, report actual z-score differences, not absolute, as per #70 
  - [x] TEST
- [x] Fix initial validation at the beginning of ```qmethod() (is.numeric() | is.integer)``` (and change error message accordingly), as per Frans' message
- [x] Edit error message: `"Q method input: The distribution of items was set as non-forced and the distribution provided is not suitable (it is the wrong length or it is non numerical)"` for clarity, as per Sèbastien's email
- [x] Avoid scientific notation in results as per #73. Now avoided when 'printing' the results
  - [x] TEST
- [x] Set the argument ```forced``` with no default --so that the user explicitly knows whether they're doing forced vs non-forced OR add an additional check in the code to find whether the distribution was not forced, and add an according warning (to avoid people running 'forced' analysis where the data was non-forced)
- [x] Double check that the fix for #17 is there (and close the issue)
- [x] Add function as per #69 (and test with `plot(), print(), summary()`)
- [x] Test the above, incl. R CMD build & check, and commit

**Comment by maxheld83** [comment]
looks great!
Did you have a chance to look at the current version of my `import*.R` and `make.cards.R` functions in #52 in the meantime @aiorazabala ? Are they any closer to merge-ability and CRAN? :pray: :smile:

**Comment by maxheld83** [comment]
Ps.: if you want to, we can also raise *Milestones* for future releases here on github, and then allocate issues to these Milestones, as they are expected to be completed for some release.

**Comment by maxheld83** [comment]
I just made sure that #17 is, in fact, closed. So that's done.

May I suggest that in future, we might add even the smaller stuff as the above as individual, atomic issues @aiorazabala ? I think that might make it easier to navigate them, make sure we've got them covered and avoid duplicate efforts.

To align issues with timeframes, we now have the milestones feature.

**Comment by aiorazabala** [comment]
Agree
