### ISSUE TITLE
Conference Call 1

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#79]
**2015-02-27 10:00 AM (London time)***

- [x] Check-In: Interest in Q / Background
- [x] How can we make git(hub) flow work as best as possible for everyone + insure great quality? #38 
- [x] What might be a suitable release cycle + process? #80 

- [x] Update on new functions and documentation, plan for release? (especially #52)
- [x] Compatibility with HTMLQ5 (front end? at least import the data) (close #22 ?!)
- [x] support for named factors #69
- [x] Online demo: add feature to upload your own data #42 (can we close?)
- [x] equamax rotation #28 Want to inform to Noori?
- [x] strengthen user discretion, statistical issues (NO Q-IDEOLOGY) #21 (?)

- [x] GUI and cookbook - ready to share it with small group to try and then announce?

- [x] community outreach: how/what do we communicate to the qmethod list (and other outlets). Should/can there be a presentation at the annual conference? #27 

- [x] add/prioritize remaining issues

**Comment by maxheld83** [comment]
our conference calls can also be assigned to milestones.

**Comment by maxheld83** [comment]
I think that the shiny GUI @aiorazabala wrote will be pretty huge (especially since many Q methodologists seem to be not tooo tech-savvy).

I was wondering:

- what might be a perspective for deploying it, if it captures some interests (since RStudio free offering is pretty limited.). Maybe we ought to think about approaching [ISSSS](http://qmethod.org/issss) for putting out a little bit of money to have this hosted somewhere?
- where does the source of the shiny app live? Can it live in here, or does it need its own repo?
- where do we track issues for the GUI?
- can we implement the existing, static visualizations (array.viz.R) via ggplot2 on shiny?
- (very exciting) what might be *interactive* visualizations in shiny via `ggvis` we can think of?

**Comment by maxheld83** [comment]
**re: Community Outreach**

I'd really like it if we could get more people off the Q list on here (github issues) for a **productive** discussion on q methodology software.
Who knows, maybe we can even get one or the other contributor.

**Comment by maxheld83** [comment]
I'll document the conference call we just had in the respective issues, and raise new ones:

- #82 announce 1.3.0 on email list
- #83 raise funds or something for hosted version of shiny app (pie-in-the-sky)

**Comment by maxheld83** [comment]
uh, I forgot about two questions about the GUI @aiorazabala, before I close this:

> - [ ] where does the source of the shiny app live? Can it live in here, or does it need its own repo?
> - [ ] where do we track issues for the GUI?

**Comment by aiorazabala** [comment]
I believe this can be closed
